#!/usr/bin/python
#
# Copyright (c) rPath, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#


"""
Send out a single advisory if available for a given package on a
given platform.
"""

import os
import sys

from conary.lib import util
sys.excepthook = util.genExcepthook()

platform = sys.argv[1]
mirrorballPath = os.environ['HOME'] + '/hg/mirrorball'

sys.path.insert(0, mirrorballPath)

from updatebot import log
from updatebot import bot
from updatebot import config

log.addRootLogger()

cfg = config.UpdateBotConfig()
cfg.read(mirrorballPath + '/config/%s/updatebotrc' % platform)

obj = bot.Bot(cfg)

obj._pkgSource.load()

advisor = obj._advisor
updater = obj._updater

advisor.load()

import epdb ; epdb.st()
