#!/usr/bin/env python
#
# Copyright (c) SAS Institute, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


import logging
import os
import sys

import _scriptsetup

from conary.lib import util
sys.excepthook = util.genExcepthook()
import epdb

from updatebot.artifactory import Bot
from updatebot import config


log = logging.getLogger(__name__)


cfg = config.UpdateBotConfig()
cfg.read(os.path.abspath('../') + '/config/%s/updatebotrc' % sys.argv[1])
obj = Bot(cfg)
recreate = cfg.recreate
trvMap, fail = obj.create(rebuild=True, recreate=recreate)

epdb.st()

for source in sorted(trvMap.keys()):
    for binanry in job[source]:
        if ':' not in binary[0]:
            print '%s=%s[%s]' % binary
