#!/usr/bin/python
#
# Copyright (c) 2008-2010 rPath, Inc.
#
# This program is distributed under the terms of the Common Public License,
# version 1.0. A copy of this license should have been distributed with this
# source file in a file called LICENSE. If it is not present, the license
# is always available at http://www.rpath.com/permanent/licenses/CPL-1.0.
#
# This program is distributed in the hope that it will be useful, but
# without any warranty; without even the implied warranty of merchantability
# or fitness for a particular purpose. See the Common Public License for
# full details.
#

import os

from updatebot.cmdline import display
from updatebot.cmdline.simple import main
from updatebot import ordered

def update(cfg):
    if cfg.platformName == 'rhel':
        import rhnmirror

        mcfg = rhnmirror.MirrorConfig()
        mcfg.read(os.path.join(cfg.configPath, 'erratarc'))

        errata = rhnmirror.Errata(mcfg)
        errata.fetch()

        bot = ordered.Bot(cfg, errata)
    else:
        bot = ordered.Bot(cfg, None)

        if cfg.platformName == 'sles':
            from errata.sles import AdvisoryManager as Errata

        elif cfg.platformName == 'sles11':
            from errata.sles11 import AdvisoryManager11 as Errata

        elif cfg.platformName == 'centos':
            from errata.centos import AdvisoryManager as Errata

        else:
            raise RuntimeError, 'no errata source found for %s' % cfg.platformName

        errata = Errata(bot._pkgSource)
        bot._errata._errata = errata

    trvMap = bot.update()
    if trvMap:
        print 'Updated the following troves:'
        print display.displayTroveMap(trvMap)

    return 0

if __name__ == '__main__':
    import sys
    from conary.lib import util
    sys.excepthook = util.genExcepthook(debug=False)

    sys.exit(main(sys.argv, update))
