#!/usr/bin/python
#
# Copyright (c) SAS Institute, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


from updatebot.cmdline import display
from updatebot.cmdline.simple import main
from updatebot import current

def buildgroups(cfg):
    bot = current.Bot(cfg)

    trvMap = bot.buildgroups()

    if trvMap:
        print 'Updated the following troves:'
        print display.displayTroveMap(trvMap)

    return 0

if __name__ == '__main__':
    import sys
    from conary.lib import util
    sys.excepthook = util.genExcepthook(debug=False)

    sys.exit(main(sys.argv, buildgroups))

