#!/usr/bin/python
#
# Copryright (c) 2008 rPath, Inc.
#

"""
Script for cooking groups defined in the updatebot config.
"""

from header import *

grpTrvs = set()
for flavor in cfg.groupFlavors:
    grpTrvs.add((cfg.topSourceGroup[0], cfg.topSourceGroup[1], flavor))
grpTrvMap = builder.build(grpTrvs)

print "built:\n"

display(grpTrvMap)
