#!/usr/bin/python
#
# Copryright (c) 2008 rPath, Inc.
#

"""
Script for cooking groups defined in the updatebot config.
"""

import os
import sys

sys.path.insert(0, os.environ['HOME'] + '/hg/rpath-xmllib')
sys.path.insert(0, os.environ['HOME'] + '/hg/conary')
sys.path.insert(0, os.environ['HOME'] + '/hg/mirrorball')

from updatebot import log
from updatebot import build
from updatebot import config

log.addRootLogger()
cfg = config.UpdateBotConfig()
cfg.read(os.environ['HOME'] + '/hg/mirrorball/config/ubuntu/updatebotrc')

builder = build.Builder(cfg)


trvs = set()
label = cfg.topSourceGroup[1]
for pkg in sys.argv[1:]:
    trvs.add((pkg, label, None))
trvMap = builder.build(trvs)

print "built:\n"

def displayTrove(nvf):
    flavor = ''
    if nvf[2] is not None:
        flavor = '[%s]' % nvf[2]

    return '%s=%s%s' % (nvf[0], nvf[1], flavor)

for srcTrv in trvMap.iterkeys():
    print displayTrove(srcTrv)
    for binTrv in trvMap[srcTrv]:
        print " " * 4, displayTrove(binTrv)
