#!/usr/bin/python
#
# Copryright (c) 2008-2009 rPath, Inc.
#

"""
Script for cooking groups defined in the updatebot config.
"""

from header import *

builder = build.Builder(cfg, ui, rmakeCfgFn='rmakerc-groups')

grpTrvMap = builder.build((cfg.topSourceGroup, ))

print "built:\n"

display(grpTrvMap)
