#!/usr/bin/python
#
# Copyright (c) SAS Institute, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


"""
Script for cooking groups defined in the updatebot config.
"""

from header import *

from updatebot.lib import util
util.setupDebugHandler()

from conary.conaryclient import cmdline

from updatebot.build.dispatcher import MultiVersionDispatcher as Dispatcher

if len(sys.argv) < 3:
    usage()

trvs = set()
for pkg in sys.argv[2:]:
    n, v, f = cmdline.parseTroveSpec(pkg)
    trvs.add((n, v, f))

builder = build.Builder(cfg, ui, rmakeCfgFn='rmakerc-groups')
disp = Dispatcher(builder, 20, waitForAllVersions=False)
trvMap, failed = disp.buildmany(trvs)

print "built:\n"

display(trvMap)
