#!/usr/bin/python
#
# Copryright (c) 2008-2009 rPath, Inc.
#

"""
Script for cooking packages with updatebot config.
"""

import os

from header import *
from updatebot import errors
from updatebot import conaryhelper

if len(sys.argv) < 3:
    usage()

helper = conaryhelper.ConaryHelper(cfg)

def validateInput(input):
    for pkgName in input:
        try:
            manifest = helper.getManifest(pkgName)
        except errors.NoManifestFoundError, e:
            yield pkgName, None
            continue
        paths = [ os.path.basename(x) for x in manifest ]
        yield pkgName, tuple(paths)
    raise StopIteration

trvs = set()
label = cfg.topSourceGroup[1]
for pkg, manifest in validateInput(sys.argv[2:]):
    trvs.add((pkg, label, None, manifest))
trvMap = builder.build(trvs)

print "built:\n"

display(trvMap)
