#!/usr/bin/python
#
# Copyright (c) SAS Institute, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


"""
Script for cooking groups defined in the updatebot config.
"""

from header import *

from updatebot.ordered import Bot

from conary.conaryclient import cmdline

bot = Bot(cfg, ui)

results = []
for trvSpec in sys.argv[2:]:
    n, v, f = cmdline.parseTroveSpec(trvSpec)
    group = bot._groupmgr.getGroup(version=v)
    results.append(group.buildmany())
else:
    group = bot._groupmgr.getGroup()
    results.append(group.buildmany())

import time
while [ x for x in results if not x.isDone ]:
    time.sleep(3)

grpTrvMap = {}
for res in results:
    grpTrvMap.update(res.results)

print "built:\n"

display(grpTrvMap)
