#!/bin/bash
#
# Copyright (c) 2009 rPath, Inc.
#
# This program is distributed under the terms of the Common Public License,
# version 1.0. A copy of this license should have been distributed with this
# source file in a file called LICENSE. If it is not present, the license
# is always available at http://www.rpath.com/permanent/licenses/CPL-1.0.
#
# This program is distributed in the hope that it will be useful, but
# without any warranty; without even the implied warranty of merchantability
# or fitness for a particular purpose. See the Common Public License for
# full details.
#

platform=$1
shift

if [ "$2" != "" ] ; then
    context=$2
else
    context="x86"
fi

# magic to determine where the script lives
mirrorballpath=$(cd ${0%/*} && cd .. && pwd -P)
platformConfig="$mirrorballpath/config/$platform/conaryrc"

if [ ! -f $platformConfig ] ; then
    echo "No conaryrc found for platform $platform in checkout $mirrorballpath"
    exit 1
fi

buildLabel=$(conary config \
    --skip-default-config \
    --config-file $platformConfig \
    | grep buildLabel | awk '{print $2}')

autoLoad=""
autoLoadPackages="
    baserequires
    package
    buildpackage
    cpackage
    autopackage
    derived
    fileset
    group
    capsule
    derivedcapsule
    groupinfo
    redirect
    userinfo
"

for pkg in $autoLoadPackages ; do
    eval cvc cook \
        --skip-default-config \
        --config-file $platformConfig \
        --context $context \
        --no-deps \
        $autoLoad \
        $pkg --debug-all
    autoLoad="$autoLoad --config \"autoLoadRecipes $pkg=$buildLabel\""
done
