#!/usr/bin/python
#
# Copryright (c) 2008-2009 rPath, Inc.
#

"""
Script for cooking groups defined in the updatebot config.
"""

from header import *

from updatebot.lib import util
util.setupDebugHandler()

from conary.conaryclient import cmdline

from updatebot.build.dispatcher import MultiVersionDispatcher as Dispatcher

if len(sys.argv) < 3:
    usage()

trvs = set()
for pkg in sys.argv[2:]:
    n, v, f = cmdline.parseTroveSpec(pkg)
    trvs.add((n, v, f))

builder = build.Builder(cfg, ui, rmakeCfgFn='rmakerc-groups')
disp = Dispatcher(builder, 20, waitForAllVersions=False)
trvMap, failed = disp.buildmany(trvs)

print "built:\n"

display(trvMap)
