#!/usr/bin/python
#
# Copyright (c) rPath, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#


"""
Script for cooking groups defined in the updatebot config.
"""

from header import *

from updatebot.ordered import Bot

from conary.conaryclient import cmdline

bot = Bot(cfg, ui)

results = []
for trvSpec in sys.argv[2:]:
    n, v, f = cmdline.parseTroveSpec(trvSpec)
    group = bot._groupmgr.getGroup(version=v)
    results.append(group.buildmany())
else:
    group = bot._groupmgr.getGroup()
    results.append(group.buildmany())

import time
while [ x for x in results if not x.isDone ]:
    time.sleep(3)

grpTrvMap = {}
for res in results:
    grpTrvMap.update(res.results)

print "built:\n"

display(grpTrvMap)
