#!/usr/bin/python
#
# Copyright (c) SAS Institute, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


"""
Script for cooking packages with updatebot config.
"""

import os

from header import *
from updatebot import errors
from updatebot import conaryhelper

if len(sys.argv) < 3:
    usage()

helper = conaryhelper.ConaryHelper(cfg)

def validateInput(input):
    for pkgName in input:
        try:
            manifest = helper.getManifest(pkgName)
        except errors.NoManifestFoundError, e:
            yield pkgName, None
            continue
        paths = [ os.path.basename(x) for x in manifest ]
        yield pkgName, tuple(paths)
    raise StopIteration

trvs = set()
label = cfg.topSourceGroup[1]
for pkg, manifest in validateInput(sys.argv[2:]):
    trvs.add((pkg, label, None, manifest))
trvMap = builder.build(trvs)

print "built:\n"

display(trvMap)
