#!/usr/bin/python
#
# Copryright (c) 2008-2009 rPath, Inc.
#

"""
Script for cooking groups defined in the updatebot config.
"""

from header import *

from updatebot.ordered import Bot

from conary.conaryclient import cmdline

bot = Bot(cfg, ui)

results = []
for trvSpec in sys.argv[2:]:
    n, v, f = cmdline.parseTroveSpec(trvSpec)
    group = bot._groupmgr.getGroup(version=v)
    results.append(group.buildmany())
else:
    group = bot._groupmgr.getGroup()
    results.append(group.buildmany())

import time
while [ x for x in results if not x.isDone ]:
    time.sleep(3)

grpTrvMap = {}
for res in results:
    grpTrvMap.update(res.results)

print "built:\n"

display(grpTrvMap)
