#!/usr/bin/python
#
# Copyright (c) SAS Institute, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


"""
Script for committing a set of rmake jobs one at a time.
"""

import sys
import logging

from header import *

log = logging.getLogger('script')

jobIds = sys.argv[2:]

for jobId in jobIds:
    log.info('starting commit of %s' % jobId)
    builder.commit(jobId)
    log.info('commit of %s completed' % jobId)
