#!/usr/bin/python
#
# Copyright (c) rPath, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#


"""
Script for diffing the contents of a label against the latest binary
group version.
"""

import os
import sys
import logging

mirrorballDir = os.path.abspath('../')
sys.path.insert(0, mirrorballDir)

if 'CONARY_PATH' in os.environ:
    sys.path.insert(0, os.environ['CONARY_PATH'])

import conary
import updatebot

print >>sys.stderr, 'using conary from', os.path.dirname(conary.__file__)
print >>sys.stderr, 'using updatebot from', os.path.dirname(updatebot.__file__)

from conary.lib import util
sys.excepthook = util.genExcepthook()

from conary import checkin

from updatebot import config
from updatebot.bot import Bot
from updatebot import log as logSetup

logSetup.addRootLogger()
log = logging.getLogger('script')

def usage():
    print 'usage: %s <platform>' % sys.argv[0]
    sys.exit(1)

platform = sys.argv[1]
if platform not in os.listdir(mirrorballDir + '/config'):
    usage()

confDir = mirrorballDir + '/config/' + platform

cfg = config.UpdateBotConfig()
cfg.read(confDir + '/updatebotrc')

bot = Bot(cfg)
updater = bot._updater
helper = updater._conaryhelper

labelPkgs = updater.getSourceVersions()
groupPkgs = updater._conaryhelper.getSourceTroves(cfg.topGroup)

lks = set([ x for x in labelPkgs.keys()
            if not updater._fltrPkg(x[0].split(':')[0]) ])
gks = set([ x for x in groupPkgs.keys()
            if not updater._fltrPkg(x[0].split(':')[0]) ])

newPkgs = lks.difference(gks)

toRemove = set()
for srcTrv in newPkgs:
    toRemove.add(srcTrv)
    toRemove.update(labelPkgs[srcTrv])

ccfg = helper._ccfg
repos = helper._repos

# This will prompt for confirmation.
for rspec in sorted(toRemove):
    n, v, f = rspec
    spec = '%s=%s' % (n, v)
    if f is not None:
        spec += '[%s]' % f

    checkin.markRemoved(ccfg, repos, spec)

import epdb; epdb.st()
