#!/usr/bin/python
#
# Copyright (c) rPath, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#


import os
import sys
import logging

mirrorballDir = os.path.abspath('../')
sys.path.insert(0, mirrorballDir)

if 'CONARY_PATH' in os.environ:
    sys.path.insert(0, os.environ['CONARY_PATH'])

from updatebot import pkgsource
from updatebot import OrderedBot

log = logging.getLogger('tmplogger')

class Bot(OrderedBot):
    def findrelease(self, release):
        """
        Find the first point in the update stream that all packages that are
        included in a release version should be availble in the repository.
        """

        # load release reference source
        repoUrl = self._cfg.versionSources[release]
        relSrc = pkgsource.RpmSource(self._cfg, self._ui)
        relSrc.loadFromUrl(repoUrl)
        relSrc.finalize()

        relNevraMap = dict([ (x.getNevra(), x) for x in relSrc.srcPkgMap ])
        relNameMap = dict([ (x.name, x.getNevra()) for x in relSrc.srcPkgMap ])
        relNameSet = set(relNameMap.iterkeys())

        # load package source
        self._pkgSource.load()

        repo = {}
        repoNames = set()

        found = {}
        notfound = {}

        # Iterate over all upstream group versions that should exist.
        for updateId, updates in self._errata.iterByIssueDate(current=-1):
            repo.update([ (x.getNevra(), x) for x in updates ])
            repoNames.update(set([ x.name for x in updates ]))

            version = self._errata.getBucketVersion(updateId)

            log.info('checking: %s(%s)' % (version, updateId))

            foundRelease = True
            names = repoNames & relNameSet
            for name in names:
                nevra = relNameMap[name]
                if nevra not in repo:
                    foundRelease = False
                    notfound.setdefault(updateId, set()).add(nevra)
                else:
                    found.setdefault(updateId, set()).add(nevra)

            log.info('found: %s, not found: %s'
                     % (len(found.get(updateId, [])),
                        len(notfound.get(updateId, []))))

            if foundRelease:
                log.info('found %s release in %s(%s)' % (release, version,
                    updateId))
                break

        import epdb; epdb.st()

        return updateId

if __name__ == '__main__':
    import rmake
    import conary
    import updatebot

    print >>sys.stderr, 'using conary from', os.path.dirname(conary.__file__)
    print >>sys.stderr, 'using rmake from', os.path.dirname(rmake.__file__)
    print >>sys.stderr, 'using updatebot from', os.path.dirname(updatebot.__file__)

    from conary.lib import util
    sys.excepthook = util.genExcepthook()

    import rhnmirror

    from updatebot import config
    from updatebot import log as logSetup

    logSetup.addRootLogger()

    log = logging.getLogger('grouprebuild')

    confDir = mirrorballDir + '/config/%s' % sys.argv[1]

    cfg = config.UpdateBotConfig()
    cfg.read(confDir + '/updatebotrc')

    mcfg = rhnmirror.MirrorConfig()
    mcfg.read(confDir + '/erratarc')

    errata = rhnmirror.Errata(mcfg)
    errata.fetch()

    bot = Bot(cfg, errata)
    release = bot.findrelease(sys.argv[2])
    print release

    import epdb; epdb.st()
