#!/usr/bin/python
#
# Copyright (c) rPath, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#


import os
import sys

mirrorballDir = os.path.abspath('../')
sys.path.insert(0, mirrorballDir)

if 'CONARY_PATH' in os.environ:
    sys.path.insert(0, os.environ['CONARY_PATH'])

import rmake
import conary
import updatebot
from updatebot import cmdline

print >>sys.stderr, 'using conary from', os.path.dirname(conary.__file__)
print >>sys.stderr, 'using rmake from', os.path.dirname(rmake.__file__)
print >>sys.stderr, 'using updatebot from', os.path.dirname(updatebot.__file__)

from conary.lib import util
sys.excepthook = util.genExcepthook()

import logging

from updatebot import groupmgr
from updatebot import OrderedBot

log = logging.getLogger('tmplogger')

class Bot(OrderedBot):
    def generateGroupModel(self):
        """
        Generate config for standard group contents based on repository history.
        """

        # load package source
        self._pkgSource.load()

        ui = cmdline.UserInterface()

        mgr = groupmgr.GroupManager(self._cfg, ui, useMap=self._pkgSource.useMap)
        mgr.setReadOnly()

        lastAvailableUpdate = mgr.latest.errataState

        current = set()
        changes = []
        for updateId, updates in self._errata.iterByIssueDate(current=-1):
            if updateId > lastAvailableUpdate:
                log.info('%s not yet imported' % updateId)
                continue

            if updateId == 0:
                version = '5.0'
            else:
                version = self._errata.getBucketVersion(updateId)

            grp = mgr.getGroup(version=version)
            stdGroupName, stdModel = [ (x, y) for x, y in grp.iteritems()
                if x != grp._pkgGroupName ][0]

            latest = set()
            for (name, flavor, use), pkg in stdModel.iteritems():
                latest.add((name, flavor))

            added = latest - current
            removed = current - latest

            for name, flavor in added:
                if not flavor:
                    flavor = ''
                change = 'addPackage %s %s %s %s' % (updateId, stdGroupName, name, flavor)
                changes.append(change)
                log.info(change)

            for name, flavor in removed:
                if not flavor:
                    flavor = ''
                change = 'removePackage %s %s %s %s' % (updateId, stdGroupName, name, flavor)
                changes.append(change)
                log.info(change)

            current = latest

        def srtChangesByPkgName(a, b):
            cmpa = ' '.join(a.split()[1:])
            cmpb = ' '.join(b.split()[1:])
            return cmp(cmpa, cmpb)

        changes.sort(cmp=srtChangesByPkgName)

        return changes


if __name__ == '__main__':
    import rhnmirror

    from updatebot import config
    from updatebot import log as logSetup

    logSetup.addRootLogger()

    log = logging.getLogger('grouprebuild')

    cfg = config.UpdateBotConfig()
    cfg.read(mirrorballDir + '/config/%s/updatebotrc' % sys.argv[1])

    mcfg = rhnmirror.MirrorConfig()
    mcfg.read(cfg.configPath + '/erratarc')

    errata = rhnmirror.Errata(mcfg)
    errata.fetch()

    bot = Bot(cfg, errata)
    changes = bot.generateGroupModel()

    print '\n'.join(changes)

    import epdb; epdb.st()
