#!/usr/bin/python
#
# Copyright (c) 2009 rPath, Inc.
#
# This program is distributed under the terms of the Common Public License,
# version 1.0. A copy of this license should have been distributed with this
# source file in a file called LICENSE. If it is not present, the license
# is always available at http://www.rpath.com/permanent/licenses/CPL-1.0.
#
# This program is distributed in the hope that it will be useful, but
# without any warranty; without even the implied warranty of merchantability
# or fitness for a particular purpose. See the Common Public License for
# full details.
#

from header import *

from xobj import xobj

from updatebot.bot import Bot
from updatebot.lib.xobjects import XDict

pkgSource = Bot(cfg)._pkgSource
pkgSource.load()

def getLatestBin(binPkgs):
    lst = list(binPkgs)
    lst.sort()
    return lst[-1]

d = XDict()
for binName, binPkgs in pkgSource.binNameMap.iteritems():
    latest = getLatestBin(binPkgs)
    srcName = pkgSource.binPkgMap[latest].name
    if binName not in d:
        d[binName] = srcName

print xobj.toxml(d, 'pkgNameMap')
