#!/usr/bin/python
#
# Copyright (c) rPath, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#


from header import *

from xobj import xobj

from updatebot.bot import Bot
from updatebot.lib.xobjects import XDict

pkgSource = Bot(cfg)._pkgSource
pkgSource.load()

def getLatestBin(binPkgs):
    lst = list(binPkgs)
    lst.sort()
    return lst[-1]

d = XDict()
for binName, binPkgs in pkgSource.binNameMap.iteritems():
    latest = getLatestBin(binPkgs)
    srcName = pkgSource.binPkgMap[latest].name
    if binName not in d:
        d[binName] = srcName

print xobj.toxml(d, 'pkgNameMap')
