#!/usr/bin/python
#
# Copyright (c) 2011 rPath, Inc.
#
# This program is distributed under the terms of the Common Public License,
# version 1.0. A copy of this license should have been distributed with this
# source file in a file called LICENSE. If it is not present, the license
# is always available at http://www.rpath.com/permanent/licenses/CPL-1.0.
#
# This program is distributed in the hope that it will be useful, but
# without any warranty; without even the implied warranty of merchantability
# or fitness for a particular purpose. See the Common Public License for
# full details.
#

import os
import sys
from lxml import etree
import urllib2

mirrorballDir = os.path.abspath('../')
sys.path.insert(0, mirrorballDir)

from conary.lib import util
sys.excepthook = util.genExcepthook()

#import logging
#import updatebot.log
#
#updatebot.log.addRootLogger()
#log = logging.getLogger('noverrata')
#
#from updatebot import config
#
#cfg = config.UpdateBotConfig()
#cfg.read(mirrorballDir + '/config/%s/updatebotrc' % sys.argv[1] )


def fetchIdMap(doc, selector):
    idMap = {}
    for option in doc.xpath(selector):
        value = option.get('value')
        if value:
            idMap[option.text] = value
    return idMap

def fetchFamilyIdMap(doc):
    return fetchIdMap(doc, '//select[@id="familyId"]/option')

def fetchProductIdMap(doc):
    return fetchIdMap(doc, '//select[@id="productId"]/option')

def getBuildIds(doc):
    hrefs = [x.attrib['href'] for x in
             doc.xpath("//ul[@class='links']/li/a[@href]")]
    buildIds = [x.rsplit('?buildid=', 1)[1] for x in hrefs]
    return buildIds

def getTail(doc, selector, content):
    tails = [x.tail for x in doc.xpath(selector) if x.text == content]
    if tails:
        return tails[0]
    return None

def getCreateDate(doc):
    return getTail(doc, "//div[@class='info-section']/span", 'Creation Date: ')

def getPatchId(doc):
    patchId = getTail(doc, "//div[@class='readme-section']//b", 'Patch:')
    if patchId is not None:
        patchId = patchId.strip() # leading whitespace
        patchId, version = patchId.rsplit('-', 1)
        return patchId, version
    else:
        return None, None

def getDoc(fobj):
    return etree.parse(fobj, etree.HTMLParser())

def getIndex(argStr = '', **kw):
    URI = 'http://download.novell.com/patch/finder/index.jsp' + argStr
    return urllib2.urlopen(URI % kw)

def getBuild(buildId):
    # use cached buildId if we have it -- store in DB rather than
    # filesystem later if anyone cares...
    try:
        return file('bldids/%s' %buildId, 'r')
    except:
        cache = file('bldids/%s' %buildId, 'w')
        sys.stderr.write('Fetching buildid %s\n' % buildId)
        cache.write(urllib2.urlopen(
            'http://download.novell.com/Download?buildid=' + buildId).read())
        cache.close()
        return getBuild(buildId)




sys.stderr.write('Fetching toplevel index...\n')
toc = getDoc(getIndex())
familyIdMap = fetchFamilyIdMap(toc)
# Limit what we crawl to products we might care about
familyIdMap = dict([(x, familyIdMap[x]) for x in familyIdMap.keys()
                    if 'SUSE Linux Enterprise' in x])

productIdMaps = {}
for familyName in familyIdMap.keys():
    familyId = familyIdMap[familyName]
    sys.stderr.write('Fetching index for product %s...\n' % familyName)
    fdoc = getDoc(getIndex('?action=onGetMainBodyAction&familyId=%(familyId)s',
                           familyId=familyId))

    productIdMap = fetchProductIdMap(fdoc)
    # pare down more if we care
    productIdMap = dict([(x, productIdMap[x]) for x in productIdMap.keys()
                         if 'SUSE Linux Enterprise' in x])
    productIdMaps[familyId] = productIdMap

    for productName in productIdMap.keys():
        productId = productIdMap[productName]
        sys.stderr.write('Fetching index for version %s...\n' % productName)
        prod = getDoc(getIndex('?action=onGetMainBodyAction'
            '&familyId=%(familyId)s&xf=%(familyId)s'
            '&xp=%(familyId)s_%(productId)s',
            familyId=familyId, productId=productId))

        buildIds = getBuildIds(prod)

        for buildId in buildIds:
            patch = getDoc(getBuild(buildId))
            date = getCreateDate(patch)
            patchId, version = getPatchId(patch)
            if (date is not None and
                patchId is not None and
                version is not None):
                sys.stdout.write('%s\t%s\t%s\n' %(version, patchId, date))
