#!/usr/bin/python
#
# Copyright (c) SAS Institute, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


import sys
import itertools

from conary import trove
from conary import conarycfg
from conary import conaryclient
from conary.conaryclient import cmdline

if __name__ == '__main__':
    cfg = conarycfg.ConaryConfiguration(True)
    client = conaryclient.ConaryClient(cfg)
    trvSpec = cmdline.parseTroveSpec(sys.argv[1])

    nvfLst = client.repos.findTrove(cfg.installLabelPath, trvSpec)
    sources = client.repos.getTroveInfo(trove._TROVEINFO_TAG_SOURCENAME, nvfLst)

    srcreq = set()
    for (n, v, f), src in itertools.izip(nvfLst, sources):
        sn = src()
        sv = v.getSourceVersion()

        srcreq.add((sn, sv))

    nvfmap = {}
    for sn, sv in srcreq:
        nvfmap[(sn, sv)] = client.repos.getTrovesBySource(sn, sv)

    for (sn, sv), trvs in nvfmap.iteritems():
        print '%s=%s' % (sn, sv)
        vn = {}
        for n, v, f in trvs:
            vn.setdefault(v, set()).add(n)
        for v in reversed(sorted(vn)):
            print
            for n in sorted(vn[v]):
                print '    %s=%s' % (n, v)
