#!/usr/bin/python
#
# Copyright (c) SAS Institute, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


import os
import sys
#import time

sys.path.insert(0, os.path.abspath('../'))

from conary.lib import util
sys.excepthook = util.genExcepthook()

from updatebot import bot, config, log

#logfile = '%s_%s.log' % (sys.argv[0], time.strftime('%Y-%m-%d_%H%M%S'))
#log.addRootLogger(logfile)
log.addRootLogger()


cfg = config.UpdateBotConfig()
cfg.read(os.path.abspath('../') + '/config/%s/updatebotrc' % sys.argv[1])
obj = bot.Bot(cfg)
recreate = cfg.recreate
trvMap = obj.create(recreate=recreate)

import epdb ; epdb.st()

for job in trvMap:
    for source in sorted(job):
        for bin in job[source]:
            if ':' not in bin[0]:
                print '%s=%s[%s]' % bin
