#!/usr/bin/python
#
# Copyright (c) SAS Institute, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


"""
Script for cooking packages with updatebot config.
"""

from header import *

import logging
log = logging.getLogger('scripts.markremoved')

from updatebot import conaryhelper
from updatebot.lib.util import askYn

if len(sys.argv) < 3:
    usage()

helper = conaryhelper.ConaryHelper(cfg)

from conary.conaryclient import cmdline

trvSpecs = set([ cmdline.parseTroveSpec(x) for x in sys.argv[2:] ])

removedSpecs, cs = helper.markremoved(trvSpecs, removeSources=True)

log.info('commiting will remove the following trove specs')
for spec in sorted(removedSpecs):
    log.info('removing: %s=%s[%s]' % spec)

if askYn('remove troves? (y/N):', default=False):
    log.info('committing')
    helper._repos.commitChangeSet(cs)
    log.info('committed')
else:
    log.info('not committed')
