#!/usr/bin/python
#
# Copyright (c) SAS Institute, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


"""
Script for comparing two package sources.
"""

import os
import sys

mirrorballDir = os.path.abspath('../')
sys.path.insert(0, mirrorballDir)

if 'CONARY_PATH' in os.environ:
    sys.path.insert(0, os.environ['CONARY_PATH'])

import conary
import updatebot

print >>sys.stderr, 'using conary from', os.path.dirname(conary.__file__)
print >>sys.stderr, 'using updatebot from', os.path.dirname(updatebot.__file__)

from conary.lib import util
sys.excepthook = util.genExcepthook()

from updatebot import log
from updatebot import config
from updatebot import pkgsource

log.addRootLogger()

cfg1 = config.UpdateBotConfig()
cfg1.platformName = 'rhel 6 client'
cfg1.synthesizeSources = True

cfg2 = config.UpdateBotConfig()
cfg2.platformName = 'rhel 6 workstation'
cfg2.synthesizeSources = True

cfg3 = config.UpdateBotConfig()
cfg3.platformName = 'rhel 6 server'
cfg3.synthesizeSources = True

repositoryUrl = 'http://install.rdu.rpath.com/rhnmirror/'

cfg1.configLine('repositoryUrl %s' % repositoryUrl)
cfg2.configLine('repositoryUrl %s' % repositoryUrl)
cfg3.configLine('repositoryUrl %s' % repositoryUrl)

cfg1.configLine('repositoryPaths rhel-i386-client-6')
cfg1.configLine('repositoryPaths rhel-i386-client-optional-6')
cfg1.configLine('repositoryPaths rhel-x86_64-client-6')
cfg1.configLine('repositoryPaths rhel-x86_64-client-optional-6')

cfg2.configLine('repositoryPaths rhel-i386-workstation-6')
cfg2.configLine('repositoryPaths rhel-i386-workstation-optional-6')
cfg2.configLine('repositoryPaths rhel-x86_64-workstation-6')
cfg2.configLine('repositoryPaths rhel-x86_64-workstation-optional-6')

cfg3.configLine('repositoryPaths rhel-i386-server-6')
cfg3.configLine('repositoryPaths rhel-i386-server-optional-6')
cfg3.configLine('repositoryPaths rhel-x86_64-server-6')
cfg3.configLine('repositoryPaths rhel-x86_64-server-optional-6')

client = pkgsource.PackageSource(cfg1, None)
workstation = pkgsource.PackageSource(cfg2, None)
server = pkgsource.PackageSource(cfg3, None)

client.load()
workstation.load()
server.load()

import epdb; epdb.st()
