#!/usr/bin/python
#
# Copyright (c) SAS Institute, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


import os
import sys
import shutil
import logging

mirrorballDir = os.path.abspath('../')
sys.path.insert(0, mirrorballDir)

from updatebot import OrderedBot

log = logging.getLogger('tmplogger')

class Bot(OrderedBot):
    def _getAllVersions(self, name):
        """
        Get all of the versions of a given source.
        """

        # Find all versions of name.
        nvfs = self._updater._conaryhelper.findTrove(
            ('%s:source' % name, None, None), getLeaves=False)

        return sorted(nvfs)

    def rebuildpackages(self, names, useLatest=None,
        additionalResolveTroves=None):
        """
        Rebuild all versions of a given package in order.
        @param names: names of the packages to rebuild.
        @type names: str
        @param useLatest: A list of package names to use the latest versions of.
                          For instance, you may want to use the latest version
                          of conary to get fixed dependencies.
        @type useLatest: list(str, ...)
        @param additionalResolveTroves: List of additional trove specs to add to
                                        the resolve troves.
        @type additionalResolveTroves: list(str, ...)
        """

        nvfs = set()
        for name in names:
            trvSpecs = [ (x[0].split(':')[0], x[1], None)
                         for x in self._getAllVersions(name) ]

            # Build only the latest versions of each sources.
            latestMap = {}
            for n, v, f in reversed(sorted(trvSpecs)):
                upVer = v.trailingRevision().version
                if upVer not in latestMap:
                    latestMap[upVer] = (n, v, f)

            nvfs.update(set(latestMap.values()))

        trvMap = self._builder.rebuildmany(list(nvfs),
            useLatest=useLatest,
            additionalResolveTroves=additionalResolveTroves)

        return trvMap

    def removeSourceFiles(self, name, keepFiles=None, replaceFiles=None):
        """
        Remove all of the files from all source versions of a package that are
        not listed in keepFiles.
        @param name: name of the package to rebuild.
        @type name: str
        @param keepFiles: Set of files to keep in the source component. By
                          default manifest and CONARY will always been kept.
        @type keepFiles: set(str, ...)
        """

        if not keepFiles:
            keepFiles = set()

        if not replaceFiles:
            replaceFiles = set()

        replaceMap = dict([ (os.path.basename(x), x) for x in replaceFiles ])
        keepFiles.update(set(replaceMap.keys()))

        # Always avoid removing the CONARY file and the manifest.
        keepFiles.add('CONARY')
        keepFiles.add('manifest')

        helper = self._updater._conaryhelper

        # Get a list of source verisons.
        trvSpecs = self._getAllVersions(name)

        # Rewrite source versions by cloning old versions forward and then
        # modifying them.
        for spec in trvSpecs:
            # Clone version to tip, only need to clone if there is more than
            # one version.
            if len(trvSpecs) > 1:
                targetBranch = spec[1].branch()
                cs, newPkgs = helper.clone(targetBranch, [spec, ], commit=False)

                assert len(newPkgs) == 1
                n, v, f = newPkgs[0]

                # Commit the changeset now that it has been validated.
                log.info('commiting clone changeset')
                helper._repos.commitChangeSet(cs)
            else:
                n, v, f = spec

            # Edit the source to remove files.
            checkoutDir = helper._edit(n, version=v)
            files = set(os.listdir(checkoutDir))

            removeFiles = files - keepFiles
            for fn in removeFiles:
                helper._removeFile(checkoutDir, fn)

            replace = files & set(replaceMap.keys())
            for fn in replace:
                dest = os.path.join(checkoutDir, fn)
                log.info('replacing %s -> %s' % (replaceMap[fn], dest))
                shutil.copyfile(replaceMap[fn], dest)

            # Commit changes if anything changed.
            if removeFiles or replace:
                helper.commit(n, version=v,
                              commitMessage='automated file removal')


if __name__ == '__main__':
    import os
    import sys

    if 'CONARY_PATH' in os.environ:
        sys.path.insert(0, os.environ['CONARY_PATH'])

    import rmake
    import conary
    import updatebot

    print >>sys.stderr, 'using conary from', os.path.dirname(conary.__file__)
    print >>sys.stderr, 'using rmake from', os.path.dirname(rmake.__file__)
    print >>sys.stderr, 'using updatebot from', os.path.dirname(updatebot.__file__)

    from conary.lib import util
    sys.excepthook = util.genExcepthook()

    import rhnmirror

    from updatebot import config
    from updatebot import log as logSetup

    logSetup.addRootLogger()

    log = logging.getLogger('packagerebuild')

    confDir = mirrorballDir + '/config/%s' % sys.argv[1]

    cfg = config.UpdateBotConfig()
    cfg.read(confDir + '/updatebotrc')

    mcfg = rhnmirror.MirrorConfig()
    mcfg.read(confDir + '/erratarc')

    errata = rhnmirror.Errata(mcfg)
    errata.fetch()

    pkgNames = sys.argv[2:]
    #replaceFiles = sys.argv[3:]
    replaceFiles = None

    bot = Bot(cfg, errata)

    #for pkgName in pkgNames:
    #    bot.removeSourceFiles(pkgName, replaceFiles=replaceFiles)

    bot.rebuildpackages(pkgNames,
        useLatest=['conary', 'conary-build', 'conary-policy', 'rpm', 'capsule-kmod-import'],
        additionalResolveTroves=[
            'libelf-lgpl=rhel.rpath.com@rpath:rhel-5-devel',
            'conary=rhel.rpath.com@rpath:rhel-5-devel',
            'conary-build=rhel.rpath.com@rpath:rhel-5-devel',
            'conary-policy=rhel.rpath.com@rpath:rhel-5-devel',
            'rpm=rhel.rpath.com@rpath:rhel-5-server-devel',
            'group-os=rhel.rpath.com@rpath:rhel-5-server-devel',
            'group-rpath-packages=rhel.rpath.com@rpath:rhel-5-devel', ])

    import epdb; epdb.st()
