#!/usr/bin/python
#
# Copyright (c) rPath, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#


import os
import sys
import operator

sys.path.insert(0, os.environ['HOME'] + '/hg/rpath-xmllib')
sys.path.insert(0, os.environ['HOME'] + '/hg/conary')
sys.path.insert(0, os.environ['HOME'] + '/hg/mirrorball')

from conary.lib import util
from conary.lib.sha1helper import md5String, md5ToString
from conary import rpmhelper, files, updatecmd
sys.excepthook = util.genExcepthook()

from updatebot import bot, conaryhelper, config, log
from rpmutils import readHeader

outfile = open(sys.argv[1], 'w')
cb = updatecmd.UpdateCallback()

#import cProfile
#prof = cProfile.Profile()
#prof.enable()

log.addRootLogger()
cfg = config.UpdateBotConfig()
cfg.read(os.environ['HOME'] + '/hg/mirrorball/config/sles/updatebotrc')
obj = bot.Bot(cfg)

#prof.disable()
#prof.dump_stats('report.lsprof')

conaryhelper = obj._updater._conaryhelper
conaryclient = conaryhelper._client 

pkgMap = conaryhelper.getSourceTroves(cfg.topGroup)
sources = sorted(pkgMap.keys())

for src in sources:
    srcName = src[0].split(':')[0]
    if srcName in cfg.excludePackages:
        continue
    if srcName.startswith('group-') or srcName.startswith('info-'):
        continue
    manifest = conaryhelper.getManifest(srcName)

    pathMap = {}
    # collect up a path -> rpm package map
    for rpm in manifest:
        if 'src.rpm' in rpm:
            continue
        rpmloc = '%s/%s' %(cfg.repositoryUrl, rpm)
        h = readHeader(rpmloc)
        arch = h[rpmhelper.ARCH]
        rpmname = os.path.basename(rpm)
        d = dict.fromkeys(((util.normpath(x), arch) for x in h.paths()), rpmname)
        pathMap.update(d)
    binaries = sorted(pkgMap[src])
    flist = []
    for binary in binaries:
        name, version, flavor = binary
        flavorStr = str(flavor)
        if ':' not in name:
            continue
        if 'debuginfo' in name:
            continue
        if 'is: x86_64' in str(flavorStr):
            arch = 'x86_64'
        elif 'is: x86(' in str(flavorStr):
            arch = 'i586'
        else:
            arch = 'noarch'
        print name, version, flavor
        cs = conaryclient.createChangeSet([(name,
                                            (None, None),
                                            (version, flavor), True)],
                                          withFiles=True,
                                          withFileContents=True,
                                          callback=cb)
        tcs = [x for x in cs.iterNewTroveList()][0]
        for (pathId, path, fileId, version) in sorted(tcs.newFiles):
            f = files.ThawFile(cs.getFileChange(None, fileId), pathId)
            if hasattr(f, 'contents') and f.contents:
                cont = cs.getFileContents(pathId, fileId)[1]
                md5 = md5ToString(md5String(cont.get().read()))
                try:
                    rpm = pathMap[(path, arch)]
                except KeyError:
                    # some file we added, like a tag handler
                    continue
                flist.append((binary[0], rpm, path, md5))
    # sort based on path
    flist.sort(key=operator.itemgetter(2))
    for info in flist:
        outfile.write('\t'.join(info))
        outfile.write('\n')
    outfile.flush()
