#!/usr/bin/python

import os
import sys

sys.path.insert(0, os.path.abspath('../'))

from updatebot import log
log.addRootLogger()

from conary.lib import util
sys.excepthook = util.genExcepthook()

from updatebot import bot, config

cfg = config.UpdateBotConfig()
cfg.read(os.path.abspath('../') + '/config/%s/updatebotrc' % sys.argv[1])
obj = bot.Bot(cfg)
obj.update()
