#!/usr/bin/python
#
# Copyright (c) rPath, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#


import os
import sys

sys.path.insert(0, os.environ['HOME'] + '/hg/rpath-xmllib')
sys.path.insert(0, os.environ['HOME'] + '/hg/conary')
sys.path.insert(0, os.environ['HOME'] + '/hg/mirrorball')

from conary.lib import util
sys.excepthook = util.genExcepthook()

from conary.build import use
from updatebot import conaryhelper, config, log

log.addRootLogger()
cfg = config.UpdateBotConfig()
cfg.read(os.environ['HOME'] + '/hg/mirrorball/config/sles/updatebotrc')
helper = conaryhelper.ConaryHelper(cfg)

license = """\
#
# Copyright (c) 2008 rPath, Inc.
# This file is distributed under the terms of the MIT License.
# A copy is available at http://www.rpath.com/permanent/mit-license.html
#

"""

for name, version, flavor in helper.getSourceTroves(cfg.topGroup):
    if version.trailingLabel().asString() != cfg.topGroup[1]:
        continue

    if name.startswith('group-') or \
       name.startswith('info-') or \
       name.startswith('factory-'):
        continue

    name = name.split(':')[0]

    pkgdir = helper._checkout(name)
    recipe = os.path.join(pkgdir, '%s.recipe' % name)
    if os.path.exists(recipe):
        contents = open(recipe).read()
        if contents.startswith('#'):
            continue

        fh = open(recipe, 'w')
        fh.write(license)
        fh.write(contents)
        fh.close()

        use.setBuildFlagsFromFlavor(name, helper._ccfg.buildFlavor,
                                    error=False)

        helper._commit(pkgdir, 'Add recipe copyright license')
