#!/usr/bin/python

import os
import sys

sys.path.insert(0, os.environ['HOME'] + '/hg/mirrorball')

from updatebot import log
log.addRootLogger()

from conary.lib import util
sys.excepthook = util.genExcepthook()

from updatebot import bot, config

cfg = config.UpdateBotConfig()
cfg.read(os.environ['HOME'] + '/hg/mirrorball/config/%s/updatebotrc' % sys.argv[1])
obj = bot.Bot(cfg)
obj.update()
