#!/usr/bin/python
#
# Copyright (c) SAS Institute, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


import os
import sys
import logging

sys.path.insert(0, os.environ['HOME'] + '/hg/xobj/py')
sys.path.insert(0, os.environ['HOME'] + '/hg/mirrorball')
sys.path.insert(0, os.environ['HOME'] + '/hg/conary')
sys.path.insert(0, os.environ['HOME'] + '/hg/rmake')

from conary.lib import util
sys.excepthook = util.genExcepthook()

from updatebot import bot
from updatebot.lib import util
from updatebot import config
from updatebot import log as logger

logger.addRootLogger()

log = logging.getLogger('verifymanifest')

cfg = config.UpdateBotConfig()
cfg.read(os.environ['HOME'] + '/hg/mirrorball/config/ubuntu/updatebotrc')
b = bot.Bot(cfg)

b._pkgSource.load()

helper = b._updater._conaryhelper

pkgs = []
for n, v, f in helper.getSourceTroves(cfg.topGroup):
    n = n.split(':')[0]
    if len(v.versions) < 3 and v.trailingLabel().asString() == cfg.topGroup[1]:
        if (not n.startswith('group-') and
            not n.startswith('info-') and
            not n.startswith('factory-') and
            not n in cfg.excludePackages):
            v = helper.getLatestSourceVersion(n)
            pkgs.append((n, v.getSourceVersion()))

changed = {}
for i, (pkg, v) in enumerate(pkgs):
    srpms = list(b._pkgSource.srcNameMap[pkg])

    map = {}
    for x in srpms:
        key = '%s_%s' % (x.version, x.release)
        map[key] = x

    key = v.trailingRevision().asString().split('-')[0]
    if key not in map:
        log.info('%s (%s) version not found, using latest' % (pkg, key))
        srcPkg = b._updater._getLatestSource(pkg)
        changed[pkg] = srcPkg
        continue

    changed[pkg] = map[key]


#toBuild = set()
#for pkg in changed:
#    srcPkg = changed[pkg]
#    manifest = b._updater._getManifestFromPkgSource(srcPkg)
#    helper.setManifest(pkg, manifest)
#    metadata = b._updater._getMetadataFromPkgSource(srcPkg)
#    helper.setMetadata(pkg, metadata)

#    new = helper.getMetadata(pkg)
#    assert metadata == new

#    newManifest = helper.getManifest(pkg)
#    assert manifest == newManifest

#    helper.commit(pkg, commitMessage=cfg.commitMessage)
#    toBuild.add((pkg, cfg.topSourceGroup[1], None))

toBuild = set()
for pkg in changed.iterkeys():
    toBuild.add((pkg, cfg.topSourceGroup[1], None))

trvMap = b._builder.buildsplitarch(toBuild)

def displayTrove(nvf):
    flavor = ''
    if nvf[2] is not None:
        flavor = '[%s]' % nvf[2]

    return '%s=%s%s' % (nvf[0], nvf[1], flavor)

def display(trvMap):
    for srcTrv in trvMap.iterkeys():
        print displayTrove(srcTrv)
        for binTrv in trvMap[srcTrv]:
            print " " * 4, displayTrove(binTrv)

display(trvMap)

import epdb; epdb.st()
