#!/usr/bin/python
#
# Copyright (c) SAS Institute, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


import os
import sys

sys.path.insert(0, os.environ['HOME'] + '/hg/rpath-xmllib')
sys.path.insert(0, os.environ['HOME'] + '/hg/conary')
sys.path.insert(0, os.environ['HOME'] + '/hg/mirrorball')
sys.path.insert(0, os.environ['HOME'] + '/hg/rmake')
sys.path.insert(0, os.environ['HOME'] + '/hg/xobj/py')

from conary.lib import util
sys.excepthook = util.genExcepthook()

import logging
import updatebot.log

updatebot.log.addRootLogger()
log = logging.getLogger('test')

from updatebot import config
from updatebot import cmdline
from updatebot.update import Updater
from updatebot import pkgsource

cfg = config.UpdateBotConfig()
cfg.read(os.environ['HOME'] + '/hg/mirrorball/config/%s/updatebotrc' % sys.argv[1] )

ui = cmdline.UserInterface()

pkgSource = pkgsource.PackageSource(cfg, ui)
pkgSource.load()

updater = Updater(cfg, ui, pkgSource)

virtreqs = {}
for srcName in pkgSource.srcNameMap.iterkeys():
    if not pkgSource.srcNameMap[srcName]:
        continue
    srcPkg = updater._getLatestSource(srcName)
    for req in updater._getBuildRequiresFromPkgSource(srcPkg):
        if req[1] == 'virtual':
            if req[0] not in virtreqs:
                virtreqs[req[0]] = set()
            virtreqs[req[0]].add(srcName)

provides = {}
for binName in pkgSource.binNameMap.iterkeys():
    binPkg = updater._getLatestBinary(binName)
    for reqType in binPkg.format:
        if reqType.getName() == 'rpm:provides':
            for req in reqType.iterChildren():
                if hasattr(req, 'isspace') and req.isspace():
                    continue
                if '/' in req.name:
                    continue
                if req.name not in provides:
                    provides[req.name] = set()
                provides[req.name].add(binName)

virtreqMap = {}
for req in virtreqs.iterkeys():
    if req not in provides:
        log.warn('could not find provide %s for %s' % (req, virtreqs[req]))
        continue
    virtreqMap[req] = provides[req]

import epdb; epdb.st()
