#!/usr/bin/python
#
# Copyright (c) rPath, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#


import os
import sys

sys.path.insert(0, os.environ['HOME'] + '/hg/rpath-xmllib')
sys.path.insert(0, os.environ['HOME'] + '/hg/conary')
sys.path.insert(0, os.environ['HOME'] + '/hg/mirrorball')
sys.path.insert(0, os.environ['HOME'] + '/hg/rmake')
sys.path.insert(0, os.environ['HOME'] + '/hg/xobj/py')

from conary.lib import util
sys.excepthook = util.genExcepthook()

import logging
import updatebot.log

updatebot.log.addRootLogger()
log = logging.getLogger('test')

from updatebot import config
from updatebot import cmdline
from updatebot.update import Updater
from updatebot import pkgsource

cfg = config.UpdateBotConfig()
cfg.read(os.environ['HOME'] + '/hg/mirrorball/config/%s/updatebotrc' % sys.argv[1] )

ui = cmdline.UserInterface()

pkgSource = pkgsource.PackageSource(cfg, ui)
pkgSource.load()

updater = Updater(cfg, ui, pkgSource)

virtreqs = {}
for srcName in pkgSource.srcNameMap.iterkeys():
    if not pkgSource.srcNameMap[srcName]:
        continue
    srcPkg = updater._getLatestSource(srcName)
    for req in updater._getBuildRequiresFromPkgSource(srcPkg):
        if req[1] == 'virtual':
            if req[0] not in virtreqs:
                virtreqs[req[0]] = set()
            virtreqs[req[0]].add(srcName)

provides = {}
for binName in pkgSource.binNameMap.iterkeys():
    binPkg = updater._getLatestBinary(binName)
    for reqType in binPkg.format:
        if reqType.getName() == 'rpm:provides':
            for req in reqType.iterChildren():
                if hasattr(req, 'isspace') and req.isspace():
                    continue
                if '/' in req.name:
                    continue
                if req.name not in provides:
                    provides[req.name] = set()
                provides[req.name].add(binName)

virtreqMap = {}
for req in virtreqs.iterkeys():
    if req not in provides:
        log.warn('could not find provide %s for %s' % (req, virtreqs[req]))
        continue
    virtreqMap[req] = provides[req]

import epdb; epdb.st()
